import {
  BgColorsOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  CodeOutlined,
  ExperimentOutlined,
  FilePdfOutlined,
  FontColorsOutlined,
  KeyOutlined,
  PictureOutlined,
  QrcodeOutlined,
  SettingOutlined,
  SwapOutlined,
} from "@ant-design/icons";

import { buildOpsPath, buildPagePath, buildToolkitPath } from "./routes";
import type { NavItem, OpsTabKey, SubNavItem, ToolDirectoryItem, ToolkitTabKey } from "./types";

export const SITE_NAME = "Web Tools";
export const NAV_ITEMS: NavItem[] = [
  { key: "toolkit", label: "工具", icon: <ExperimentOutlined />, path: buildPagePath("toolkit") },
  { key: "ops", label: "运维", icon: <SettingOutlined />, path: buildPagePath("ops") },
];

export const TOOLKIT_TABS: SubNavItem<ToolkitTabKey>[] = [
  { key: "image-editor", label: "图片编辑", path: buildToolkitPath("image-editor") },
  { key: "time", label: "时间转换", path: buildToolkitPath("time") },
  { key: "horoscope", label: "星座生日", path: buildToolkitPath("horoscope") },
  { key: "almanac", label: "传统黄历", path: buildToolkitPath("almanac") },
  { key: "regex", label: "正则测试", path: buildToolkitPath("regex") },
  { key: "unit", label: "单位换算", path: buildToolkitPath("unit") },
  { key: "life", label: "人生进度", path: buildToolkitPath("life") },
  { key: "qr", label: "二维码", path: buildToolkitPath("qr") },
  { key: "pdf", label: "PDF", path: buildToolkitPath("pdf") },
  { key: "codec", label: "编码", path: buildToolkitPath("codec") },
  { key: "color", label: "颜色", path: buildToolkitPath("color") },
  { key: "text", label: "文本整理", path: buildToolkitPath("text") },
  { key: "gpt-token", label: "GPT 转换", path: buildToolkitPath("gpt-token") },
  { key: "banyiping", label: "BYP", path: buildToolkitPath("banyiping") },
];

export const TOOL_DIRECTORY_ITEMS: ToolDirectoryItem[] = [
  {
    key: "image-editor",
    title: "图片编辑",
    description: "压缩、裁剪、旋转、改尺寸。",
    category: "图像",
    path: buildToolkitPath("image-editor"),
    keywords: ["image", "图片", "压缩", "裁剪", "尺寸", "证件照"],
    icon: <PictureOutlined />,
    featured: true,
  },
  {
    key: "gpt-token",
    title: "GPT 转换",
    description: "Session / CPA / sub2api 格式整理。",
    category: "开发",
    path: buildToolkitPath("gpt-token"),
    keywords: ["gpt", "token", "session", "json", "sub2api", "codex"],
    icon: <KeyOutlined />,
    featured: true,
  },
  {
    key: "qr",
    title: "二维码",
    description: "文本和链接生成二维码。",
    category: "转换",
    path: buildToolkitPath("qr"),
    keywords: ["qr", "二维码", "链接", "分享"],
    icon: <QrcodeOutlined />,
    featured: true,
  },
  {
    key: "pdf",
    title: "PDF 工具",
    description: "常见 PDF 任务处理。",
    category: "文档",
    path: buildToolkitPath("pdf"),
    keywords: ["pdf", "文档", "合并", "转换"],
    icon: <FilePdfOutlined />,
  },
  {
    key: "regex",
    title: "正则测试",
    description: "表达式验证和文本匹配。",
    category: "开发",
    path: buildToolkitPath("regex"),
    keywords: ["regex", "正则", "匹配", "提取"],
    icon: <CodeOutlined />,
  },
  {
    key: "codec",
    title: "编码转换",
    description: "URL、Base64、JSON 互转。",
    category: "开发",
    path: buildToolkitPath("codec"),
    keywords: ["base64", "url", "json", "编码", "解码"],
    icon: <CodeOutlined />,
  },
  {
    key: "color",
    title: "颜色工具",
    description: "颜色值转换和查看。",
    category: "转换",
    path: buildToolkitPath("color"),
    keywords: ["color", "颜色", "hex", "rgb"],
    icon: <BgColorsOutlined />,
  },
  {
    key: "text",
    title: "文本整理",
    description: "清洗、拆分和统计文本。",
    category: "文本",
    path: buildToolkitPath("text"),
    keywords: ["text", "文本", "清洗", "整理", "统计"],
    icon: <FontColorsOutlined />,
  },
  {
    key: "time",
    title: "时间转换",
    description: "时间戳和日期互转。",
    category: "时间",
    path: buildToolkitPath("time"),
    keywords: ["time", "timestamp", "时间戳", "日期"],
    icon: <ClockCircleOutlined />,
  },
  {
    key: "unit",
    title: "单位换算",
    description: "常用单位快速换算。",
    category: "转换",
    path: buildToolkitPath("unit"),
    keywords: ["unit", "单位", "换算", "转换"],
    icon: <SwapOutlined />,
  },
  {
    key: "almanac",
    title: "传统黄历",
    description: "农历、节气和日期信息。",
    category: "生活",
    path: buildToolkitPath("almanac"),
    keywords: ["黄历", "农历", "节气", "日期"],
    icon: <CalendarOutlined />,
  },
  {
    key: "horoscope",
    title: "星座生日",
    description: "星座和生日日期查询。",
    category: "生活",
    path: buildToolkitPath("horoscope"),
    keywords: ["星座", "生日", "日期"],
    icon: <CalendarOutlined />,
  },
  {
    key: "life",
    title: "人生进度",
    description: "查看时间进度比例。",
    category: "生活",
    path: buildToolkitPath("life"),
    keywords: ["life", "人生", "进度", "时间"],
    icon: <ClockCircleOutlined />,
  },
  {
    key: "banyiping",
    title: "BYP",
    description: "保留的个人分析工具入口。",
    category: "文档",
    path: buildToolkitPath("banyiping"),
    keywords: ["byp", "excel", "分析"],
    icon: <ExperimentOutlined />,
  },
];

export const OPS_TABS: SubNavItem<OpsTabKey>[] = [
  { key: "features", label: "控制台", path: buildOpsPath("features") },
  { key: "logs", label: "日志查看", path: buildOpsPath("logs") },
  { key: "table", label: "数据库查询", path: buildOpsPath("table") },
];

export const OVERVIEW_ITEMS = [
  {
    label: "Image",
    title: "图片编辑器",
    description: "改尺寸、压缩体积、旋转翻转并导出证件照。",
    path: buildToolkitPath("image-editor"),
  },
  {
    label: "Tools",
    title: "效率工具箱",
    description: "生日、星座、黄历、正则、单位换算和文本整理工具。",
    path: buildToolkitPath("horoscope"),
  },
  {
    label: "Console",
    title: "控制台",
    description: "查看服务状态并管理功能开关。",
    path: buildOpsPath("features"),
  },
  {
    label: "Ops",
    title: "运维控制台",
    description: "查看日志、管理开关、查询数据库。",
    path: buildPagePath("ops"),
  },
];
